INSERT INTO `job_kvs`.`hashes` 
VALUES 
    ('field1', '{"field1":"Automobile"}', UNIX_TIMESTAMP()),
    ('field2', '{"field2":"IT - Hardware"}', UNIX_TIMESTAMP()),
    ('field3', '{"field3":"IT - Software"}', UNIX_TIMESTAMP()),
    ('field4', '{"field4":"Domestic Service"}', UNIX_TIMESTAMP()),
    ('field5', '{"field5":"Business"}', UNIX_TIMESTAMP()),
    ('field6', '{"field6":"Law"}', UNIX_TIMESTAMP()),
    ('field7', '{"field7":"Marketing"}', UNIX_TIMESTAMP()),
    ('field8', '{"field8":"Education"}', UNIX_TIMESTAMP()),
    ('field9', '{"field9":"Aeronautics"}', UNIX_TIMESTAMP()),
    ('field10', '{"field10":"Agriculture"}', UNIX_TIMESTAMP()),
    ('field11', '{"field11":"Tourism"}', UNIX_TIMESTAMP()),
    ('field12', '{"field12":"Government"}', UNIX_TIMESTAMP()),
    ('field13', '{"field13":"Science"}', UNIX_TIMESTAMP()),
    ('field14', '{"field14":"Architecture"}', UNIX_TIMESTAMP()),
    ('field15', '{"field15":"Engineering"}', UNIX_TIMESTAMP()),
    ('field16', '{"field16":"Aquaculture"}', UNIX_TIMESTAMP()),
    ('type1', '{"type1":"Temporary"}', UNIX_TIMESTAMP()),
    ('type2', '{"type2":"Part-Time"}', UNIX_TIMESTAMP()),
    ('type3', '{"type3":"Full-Time"}', UNIX_TIMESTAMP()),
    ('type4', '{"type4":"Contract"}', UNIX_TIMESTAMP()),
    ('type5', '{"type5":"Freelance"}', UNIX_TIMESTAMP()),
    ('level1', '{"level1":"Internship / OJT"}', UNIX_TIMESTAMP()),
    ('level2', '{"level2":"Fresh Grad / Entry Level"}', UNIX_TIMESTAMP()),
    ('level3', '{"level3":"Associate / Supervisor"}', UNIX_TIMESTAMP()),
    ('level4', '{"level4":"Mid-Senior Level / Manager"}', UNIX_TIMESTAMP()),
    ('level5', '{"level5":"Director / Executive"}', UNIX_TIMESTAMP()),
    ('skill1', '{"skill1":"Java"}', UNIX_TIMESTAMP()),
    ('skill2', '{"skill2":"Javascript"}', UNIX_TIMESTAMP()),
    ('skill3', '{"skill3":"NodeJS"}', UNIX_TIMESTAMP()),
    ('skill4', '{"skill4":"Angular"}', UNIX_TIMESTAMP()),
    ('skill5', '{"skill5":"HTML"}', UNIX_TIMESTAMP()),
    ('skill6', '{"skill6":"CSS"}', UNIX_TIMESTAMP()),
    ('skill7', '{"skill7":"C++"}', UNIX_TIMESTAMP()),
    ('education1', '{"education1":"Elementary"}', UNIX_TIMESTAMP()),
    ('education2', '{"education2":"High School"}', UNIX_TIMESTAMP()),
    ('education3', '{"education3":"Undergraduate"}', UNIX_TIMESTAMP()),
    ('education4', '{"education4":"Masteral"}', UNIX_TIMESTAMP()),
    ('education5', '{"education5":"Doctorate"}', UNIX_TIMESTAMP()),
    ('education6', '{"education6":"Vocational"}', UNIX_TIMESTAMP()),
    ('education7', '{"education7":"Self-Taught"}', UNIX_TIMESTAMP()),
    ('gender1', '{"gender1":"Male"}', UNIX_TIMESTAMP()),
    ('gender2', '{"gender2":"Female"}', UNIX_TIMESTAMP()),
    ('gender3', '{"gender3":"Other"}', UNIX_TIMESTAMP()),
    ('imageext1', '{"imageext1":"jpeg"}', UNIX_TIMESTAMP()),
    ('imageext2', '{"imageext2":"jpg"}', UNIX_TIMESTAMP()),
    ('imageext3', '{"imageext3":"png"}', UNIX_TIMESTAMP()),
    ('resumeext1', '{"resumeext1":"pdf"}', UNIX_TIMESTAMP());

INSERT INTO `job_kvs`.`sorted_sets`
VALUES 
    ('fields', 'field1', 1),
    ('fields', 'field2', 2),
    ('fields', 'field3', 3),
    ('fields', 'field4', 4),
    ('fields', 'field5', 5),
    ('fields', 'field6', 6),
    ('fields', 'field7', 7),
    ('fields', 'field8', 8),
    ('fields', 'field9', 9),
    ('fields', 'field10', 10),
    ('fields', 'field11', 11),
    ('fields', 'field12', 12),
    ('fields', 'field13', 13),
    ('fields', 'field14', 14),
    ('fields', 'field15', 15),
    ('fields', 'field16', 16),
    ('types', 'type1', 1),
    ('types', 'type2', 2),
    ('types', 'type3', 3),
    ('types', 'type4', 4),
    ('types', 'type5', 5),
    ('levels', 'level1', 1),
    ('levels', 'level2', 2),
    ('levels', 'level3', 3),
    ('levels', 'level4', 4),
    ('levels', 'level5', 5),
    ('skills', 'skill1', 1),
    ('skills', 'skill2', 2),
    ('skills', 'skill3', 3),
    ('skills', 'skill4', 4),
    ('skills', 'skill5', 5),
    ('skills', 'skill6', 6),
    ('skills', 'skill7', 1),
    ('educations', 'education1', 1),
    ('educations', 'education2', 2),
    ('educations', 'education3', 3),
    ('educations', 'education4', 4),
    ('educations', 'education5', 5),
    ('educations', 'education6', 6),
    ('educations', 'education7', 7),
    ('genders', 'gender1', 1),
    ('genders', 'gender2', 1),
    ('genders', 'gender3', 1),
    ('image_exts', 'imageext1', 1),   
    ('image_exts', 'imageext2', 1),
    ('image_exts', 'imageext3', 1),
    ('resume_exts', 'resumeext1', 1);